name: ci

# add at top or per job
env:
  VITE_CLIENT_ID_SPA: ${{ secrets.VITE_CLIENT_ID_SPA }}
  VITE_AUTHORITY:     ${{ secrets.VITE_AUTHORITY }}
  VITE_API_SCOPE:     ${{ secrets.VITE_API_SCOPE }}
  VITE_API_BASE_URL:  ${{ secrets.VITE_API_BASE_URL }}

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install (clean)
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      # before `npm run build`
      - name: Create .env.production
        run: |
          cat > .env.production << 'EOF'
          VITE_CLIENT_ID_SPA=${VITE_CLIENT_ID_SPA}
          VITE_AUTHORITY=${VITE_AUTHORITY}
          VITE_API_SCOPE=${VITE_API_SCOPE}
          VITE_API_BASE_URL=${VITE_API_BASE_URL}
          EOF


      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist
          if-no-files-found: error
